gem 'spreadsheet', '~> 1.0.0'

gem "rufus-scheduler", "3.0.3"
# gem 'writeexcel'
#  gem 'rubyXL' ,github: 'spree/spree_auth_devise'
# gem 'rubyXL', :https => "https://github.com/weshatheleopard/rubyXL"
# gem 'rubyXL', :git => 'https://github.com/weshatheleopard/rubyXL'
#  gem 'wrap_excel'
gem 'rubyXL'
gem 'excel_rails'