

production:
  adapter: mysql2
  database: inia_qc
  server: 192.168.0.103
  host: 192.168.0.103
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true
development:
  adapter: mysql2
  database: iniaDec
  server: localhost #192.168.0.103
  host: localhost #192.168.0.103
  port: 3306
  username: root
  password: root
  encoding: utf8
  reconnect: true


test:
  adapter: mysql2
  database: redmine_test
  host: localhost
  username: root
  password: root
  encoding: utf8

